### ISSUE TITLE
Crashes after a while

### ISSUE THREAD

**Issue by grahfmusic** [Jonator3/WaylandHue#3]
After about a minute or so I get this error message.

```
Traceback (most recent call last):
  File "/home/grahf/gits/WaylandHue/main.py", line 59, in <module>
    ScreenRGBGraber(on_new_frame)
  File "/home/grahf/gits/WaylandHue/main.py", line 34, in __init__
    self.__read_loop(pipe_r)
  File "/home/grahf/gits/WaylandHue/main.py", line 50, in __read_loop
    data = json.loads(json_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 13 (char 12)
```

**Comment by Jonator3** [comment]
The fix has been included with the Merge to the mk2 API-Modules
